export const API_ENDPOINTS = {
  auth: {
    signIn: '/auth/discord',
    me: '/auth/me',
    profile: '/auth/me/profile',
    logout: '/auth/logout',
  },
  blocks: { root: '/blocks', public: '/blocks/public' },
  properties: {
    root: '/properties',
    available: '/properties/available',
    featured: '/properties/featured',
  },
  enquiries: '/enquiries',
  recruitmentApplications: '/recruitment/applications',
  tenants: '/tenants',
  evictions: '/tenants/evictions',
  notices: {
    snapshot: '/notices/snapshot',
    snapshots: '/notices/snapshots',
    sync: '/notices/sync',
    retryGoogleSheet: '/notices/sync/google-sheet/retry',
  },
  users: '/users',
  auditLogs: '/audit-logs',
  dashboard: '/dashboard',
  personalStatistics: '/dashboard/personal',
  uploads: '/uploads/images',
  teamAgents: '/team/agents',
  settingsTeam: '/settings/team',
  accessManagement: '/access-management',
} as const;
